# Generated by Django 4.2.23 on 2025-08-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("autor", models.CharField(max_length=200)),
                ("genero", models.CharField(blank=True, default="", max_length=100)),
                ("fecha_publicacion", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
